tjrn/pje-fluxo

- segundograu/sg/(SG) Autos recebidos da secretaria pelo NCM.xml
- segundograu/sg/(SG) Controle de audiências a serem realizadas pelo NCM.xml
- segundograu/sg/(SG) Controle de audiências do NCM.xml
- segundograu/sg/(SG) Controle do NCM.xml
- segundograu/sg/(SG) Preparar ato de comunicação genérico.xml
- Ajustes e correções nos fluxos relacionados ao NCM;
- Criação do fluxo SG_PAC_GEN, responsável por preparar intimações (pessoalmente, sistema, edital, carta precatória e central de mandados) no NCM.
> Refatoracao do fluxo do NCM e criacao do PAC generico para uso no NCM

- segundograu/sg/(SG) Expedição de outros documentos.xml
Alteração de nó de sistema que lança movimentação de expedição de outros documentos. Estava apresentando erro ao expedir certidões.
> Alteração de movimentação de expedição dos documentos

- segundograu/sg/(SG) Controle de audiências do NCM.xml
Adicionada condicao que testa se o processo esta em varias tarefas antes de ser enviado ao gabinete/secretaria
> Refatoracao do controle de audiencias

- primeirograu/vciv/(VCiv) Cumprimento de decisão.xml
'Turma Recursal'-> 'instância superior'
> Alteração de texto no complemento

- segundograu/sg/(SG) Fluxo básico geral.xml
- segundograu/sg/(SG) Remessa para admissibilidade de recurso.xml
Ao deslocar OJ para vice, quando há algum deslocamento de fluxo, nao aparece para a vice.
Para isso, foi add o deslocamento de fluxo junto com o desloc. de OJ
> Master 9975 deslocar fluxo vice admissibilidade

- primeirograu/vciv/(VCiv) Controle do CEJUSC.xml
estravam dando problema em outro deslocamento
> Alteração para deslocar fluxo sem gravar variaveis. As variaveis

- primeirograu/jesp/Fluxo de redirecionamento.xml
- primeirograu/vciv/(VCiv) Processos digitalizados
- Adicionar decisão para ver se é digitalização no fluxo de
redirecionamento;
> - Adicionado fluxo para digitalização;

- segundograu/sg/(SG) Decisão colegiada como relator.xml
nenhuma selecionada. Isso irá evitar q alguns processos entrem no limbo.
> Adicionado condição para evitar q tenta lançar movimentação sem ter

- primeirograu/saj/(SAJ) Saj migracao.xml
Criada saída em todas as tarefas do fluxo para EF
> Criada saída para fluxo EF

- primeirograu/vciv/(VCiv) Fluxo básico de conhecimento.xml
> Adicinando evento no (VCiv)fluxo básico de conhecimento

- primeirograu/vciv/(VCiv) Cumprimento de decisão.xml
Inserção da movimentação 'Recebidos os autos' no primeiro grau na devolução do processo pela instância superior
> Inserção da movimentação 'Recebidos os autos' no PG na devolução do processo pelo SG

- primeirograu/vciv/(VCiv) Controle de Audiência.xml
Correção para as expressões das tarefa: (VCiv) Aguardar audiência; (VCiv) Realizar audiência.
> 14246 controle audiencia

- primeirograu/vciv/(VCiv) Preparar Ato Judicial.xml
Resolvendo problemas que ocorrem na assinatura de documentos via aplicativo token pje. Foram alterados os seguintes itens no fluxo:
Todas as tarefas de assinaturas foram marcadas como tal.
Removida a variável "confirmação de movimentação"
> Alterações para utilização do App Token PJe

- segundograu/tr/tuj/(TUJ) Fluxo básico geral.xml
- segundograu/tr/tuj/(TUJ) Sortear para um dos relatores.xml
Correção para alterar a competência dos processos que não ocorreram no fluxo de remeter para TUJ
> Correção para alterar a competência nos processos da TUJ antes do sorteio do relator

- segundograu/tr/tuj/(TUJ) Sortear para um dos relatores.xml
Alteração do Fluxo da TUJ, realizada para correção no sorteio de relatores que não estava ocorrendo corretamente. Foi criado um método exclusivo para a TUJ
> Alteração do Fluxo da TUJ para a correção do erro de internal server

- primeirograu/pp/(PP) Fluxo básico geral.xml
- primeirograu/vciv/(VCiv) Controle de Audiência.xml
- primeirograu/vciv/(VCiv) Preparar Ato Judicial.xml
Movimento processual não obrigatório ao transitar de conclusão para tarefa de assinatura
Closes #14011
> Movimento processual não obrigatório ao transitar de conclusão para tarefa de assinatura

- primeirograu/pp/(PP) Fluxo básico geral.xml
- primeirograu/vciv/(VCiv) Controle de Audiência.xml
- primeirograu/vciv/(VCiv) Preparar Ato Judicial.xml
Alteração nas tarefas de Informar dados de audiência, Assinatura de ata de audiência pelo conciliador e no fluxo PP_FBG relativa a evolução de classes.
Closes #12453, #14797 e #13557
> Controle de audiências e Evolução de Classe

- segundograu/(SG) Processos Digitalizados.xml
- segundograu/Redirecionamento de fluxo.xml
- segundograu/sg/(SG) Fluxo básico geral.xml
- segundograu/tr/(TR) Fluxo Básico Geral.xml
Commit final para o ajuste do fluxo de redirecionamento
> Update Redirecionamento de fluxo.xml

- primeirograu/pp/(PP) Fluxo básico geral.xml
Alteração para possibilitar a movimentação dos processos descritos no Redmine #14899, que estavam presos na tarefa "(PP) Evolução de classe - EFETUAR"
> #14899 - Alteração no fluxo PP

- primeirograu/vciv/(VCiv) Controle de prazos e retorno de expedientes.xml
- primeirograu/vciv/(VCiv) Elaborar Documentos.xml
Redmines: #15681 e #14333 - Criação da tarefa (VCiv) Aguardar trânsito julgado no fluxo (VCiv) Controle de prazos e retorno de expedientes e criação do subprocesso no fluxo (VCiv) Elaborar documentos.
> #15681 aguardar transito julgado

- primeirograu/ef/(EF) Conclusão para decisão genérica.xml
correão no action do fluxo (EF) Conclusão para decisão genérica de '(EF) Certificar Conclusão sem Efeito?'para '(EF) Encaminhar para despachados', seguindo orientações de @nathaliatj, na solução do REDMINE #15745.
> correão no action do fluxo (EF) Conclusão para decisão genérica

- primeirograu/vciv/(VCiv) Processos digitalizados.xml
Alteração para adicionar o tratamento aos processo que foram
digitalizados, mas que possuem dados de usuários ou advogados
definidos como Maria Ferro Peron e precisão ser retificados.
> Processos Digitalizados - Maria Ferro Peron

- primeirograu/vciv/(VCiv) Controle do CEJUSC.xml
> adicionando documento intimacao de audiencia

- segundograu/sg/(SG) Remessa para outra instância.xml
- segundograu/tr/(TR) Remessa para outra instância.xml
Conforme comentário do pull request #110 de Paulo Porto, estou resubmetendo o merge request após soluções dos conflitos.
> #16620 inclusao elementos dominio motivo remessa sg tr

- segundograu/sg/(SG) Decisão colegiada como relator.xml
Alteração para garantir que o proesso será marcada como revisado ao
passar pelo nó de revisão.
> #13904 - Alteração na Revisão do Processo no Fluxo

- segundograu/sg/(SG) Encaminhamento para outro gabinete.xml
Adicionadno Desb. Expedito ao plano para que ele possa receber
remessa
> 2 grau - Desb. Expedito pleno

- segundograu/sg/(SG) Redistribuição.xml
Correção para não encaminhar para o fluxo antigo da TR após redistribuição no SG
> Correção para não encaminhar para o fluxo antigo da TR após redistribuição no SG

- primeirograu/vciv/(VCiv) Elaborar Documentos.xml
Inclusão do tipo de documento mandado de prisão na tarefa "(VCiv) Expedir outros documentos", bem como da movimentação "Expedição de mandado", com vinculação ao documento.
> Inclusão do tipo de documento mandado de prisão na tarefa "(VCiv) Expedir outros documentos"

- primeirograu/vciv/(VCiv) Elaborar Documentos.xml
Ajustando de acordo com a versão que se encontra em produção.
> Ajuste no fluxo '(VCiv) Elaborar Documentos' de acordo com o fluxo de produção

- primeirograu/vciv/(VCiv) Controle de audiências do CEJUSC.xml
Correção na expressão de decisão para permitir entrar na tarefa "(CEJUSC) Realizar audiência"
> Correção na expressão de decisão para permitir entrar na tarefa "(CEJUSC) Realizar audiência"

- primeirograu/vciv/Redistribuíção.xml
Pull request referente aos problemas nas varas unicas de mossoró sendo incapaz de redistribuir e saindo do fluxo
> Resolução de problema na redistribuição dos processos

- primeirograu/vciv/(VCiv) Fluxo básico de conhecimento.xml
Remover var de audiencia ao entrar em analise de sec
Evitar internal server error
by luan
> Remover var de audiencia ao entrar em analise de sec Evitar internal server error by luan

- primeirograu/vciv/(VCiv) Preparar Ato de Comunicação.xml
Não sobrescrever DefaultTransition (by Luan)
> Não sobrescrever DefaultTransition (by Luan)

- primeirograu/vciv/(VCiv) Fluxo básico de conhecimento.xml
Removendo variáveis desnecessárias ao entrar em "(VCiv) Análise da secretaria"
> Alteração para remover variáveis que estavam causando erro na movimentação dos processos

- segundograu/sg/(SG) Remessa para outra instância.xml
> Saída em '(SG) Remessa para outra instância' caso um processo remetido não seja movimentado (#21102)

- segundograu/sg/(SG) Preparar ato de comunicação do acórdão.xml
Incluindo habilitação para movimentar em lote na tarefa "(SG) Acórdão assinado - CUMPRIR"
> Incluindo habilitação para movimentar em lote na tarefa "(SG) Acórdão assinado - CUMPRIR"

- primeirograu/vciv/(VCiv) Controle de suspensão.xml
Alteração solicitada por Dr. Diego
> Correção do movimento lançado ao encerrar a suspensão do processo

- segundograu/sg/(SG) Decisão colegiada como relator.xml
Alteração para enviar ao revisor substituto
Feito por Paulo Porto
> Alteração para enviar ao revisor substituto

- segundograu/tr/tuj/(TUJ) Decisão colegiada como relator.xml
Alteração no fluxo TUJ_DECCOLREL para correção de erro de falha na movimentação ao tentar enviar para Votação Antecipada.
> Update (TUJ) Decisão colegiada como relator.xml

- segundograu/sg/(SG) Decisão colegiada como relator.xml
- segundograu/sg/(SG) Fluxo básico geral.xml
- segundograu/sg/(SG) Remessa para outra instância.xml
Deletar variáveis temporárias e minuta em elaboração que pode fazer com que o processo não ande para tarefa de Remessa Para o Primeiro Grau Concluída após ter sido remetido
> (SG) Remessa para o Primeiro Grau Concluída 

- primeirograu/ef/(EF) Arquivamento.xml
- primeirograu/vciv/(VCiv) Arquivamento.xml
Alterações nos fluxos de arquivamento para lançar movimentações corretas, inativar tarefas desnecessárias e incluir novas tarefas
Solicitadas por Dr. Diego
> Alterações nos fluxos de arquivamento (remoção e adição de tarefas e correções de movimentações)

- segundograu/sg/(SG) Controle do NCM.xml
Alterando movimentos do fluxo para secretaria e gabinete
> FLUXO DO NÚCLEO DE CONCILIAÇÃO

- segundograu/sg/(SG) Controle de prazos do MP.xml
Alterações para retornar o processo diretamente ao gabinete após decorrido o prazo da intimação feita via ato ordinatório do gabinete à PGJ
> Retornar o processo diretamente ao gabinete após decorrido o prazo da intimação feita via ato ordinatório do gabinete à PGJ

- primeirograu/vciv/(VCiv) Cumprimento de decisão.xml
Evitar que processos entrem na tarefa de bacenjud em transições não relacionadas
> Remover transição "(VCiv) Bacenjud - Minutar bloqueio ou desbloqueio"

- primeirograu/vciv/(VCiv) Elaborar Documentos.xml
Exibir as tarefas Expedir Outros Documentos e Expedir Ofício para usuários que tenham perfil de Juiz.
> Exibir tarefas do fluxo para usuários com perfil de Juiz
